# Management for admin endpoints (Spring actuator)
management:
  server:
    port: 8081
    address: 0.0.0.0
    base-path: /
  endpoint:
    health:
      group:
        readiness:
          include: ping
          show-details: always
        liveness:
          include: ping
          show-details: always
      show-components: always
      show-details: always
  endpoints:
    web:
      base-path: / # change the base path from "/actuator/" to "/"
    exposure:
      include: "*"
  health:
    binders:
      enabled: false

server:
  port: 8080

spring:
  profiles:
    include: swagger
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    config-url: /v3/routers-docs/swagger-config
    url: /v3/routers-docs


quarkus:
  kubernetes-client:
    trust-certs: false
    namespace: kubeclient