apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeapi.fullname" . }}
  labels:
    {{- include "kubeapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.port }}
      protocol: TCP
      name: http-admin
  selector:
    {{- include "kubeapi.selectorLabels" . | nindent 4 }}
