apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeapi-pyp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubeapi-pyp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort | default nil }}


  selector:
    {{- include "kubeapi-pyp.selectorLabels" . | nindent 4 }}
